#!/usr/bin/env python3
#author:rangapv@yahoo.com
#14-11-24

from polygon import StocksClient 

class fetch:
        #apple = yf.Ticker("AAPL")
    def polyget(self,API_KEY):
       client = StocksClient("API_KEY")
       return client

#main BEGINS
if __name__  == "main": 
 p1 = fetch()
 print (f'client is {p1}')
 client1 = p1.polyget("080dt12muu7EP9aOOYYTb1LDEOhPsTr3")
 aggs = []
 for a in client1.list_aggs(
    "AAPL",
    1,
    "minute",
    "2022-01-01",
    "2023-02-03",
    limit=50000,
 ):
    aggs.append(a)

 print(f"aggs is {aggs}")
