#Author:rangapv@yahoo.com
#26-11-24
#debian based so apt-get works

FROM python:3.13.0-slim-bookworm

RUN apt update

RUN apt install -y vim

COPY requirements.txt /tmp/requirements.txt

WORKDIR /tmp

RUN pip3 install -r requirements.txt

COPY stokpoly.py /

COPY ./.env /

WORKDIR /

EXPOSE 8501

CMD ["python3", "-m", "streamlit", "run", "stokpoly.py", "--server.port=8501", "--server.address=0.0.0.0"]
